### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by myxsolis** [Globox1997/MedievalWeapons#101]
Some of the weapons have missing textures. I'm using the latest version of the mod.

![issue](https://user-images.githubusercontent.com/61819520/215385349-10e22e63-d1f7-4b2f-8c5a-f3569b63e9f5.PNG)

**Comment by sargeow** [comment]
same issue, same exact weapons causing the issue. mod version 1.4.2: running on Quilt version 1.19.2: loader version 17.11 (latest)

**Comment by Marcarrones** [comment]
I'm having the same issue. In my case I think it's due to an incompatibility with [brrp](https://modrinth.com/mod/brrp) used by [Extended Block Shapes](https://www.curseforge.com/minecraft/mc-mods/extended-block-shapes/relations/dependencies) . 

In theory, brrp only deprecates arrp's classes and methods which should allow arrp mods (medieval weapons) to use brrp.

I'm using Fabric 0.14.12 1.19.2.

Here's the log with only Medieval Weapons and Extended Block Shapes (disabling aarp).
[latest.log](https://github.com/Globox1997/MedievalWeapons/files/10570551/latest.log)

**Comment by AaelusOttodean** [comment]
I am as well, and can't figure out why. I own a server, and it upsets me that none of us can use any of the cool weapons. If anyone has any fixes, please let me know!

**Comment by Globox1997** [comment]
Yes it happens due to an incompatibility with brrp. Medieval Weapons uses ARRP.

**Comment by PigeonMatt** [comment]
you can fix that, using this mod https://www.curseforge.com/minecraft/mc-mods/arrp/files

**Comment by Globox1997** [comment]
With the latest version of this mod you can use either BRRP or ARRP but not both at the same time.
Be aware that other mods can include one of these.
