### ISSUE TITLE
Minecraft won't launch

### ISSUE THREAD

**Issue by porygonow** [Globox1997/MedievalWeapons#38]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'medievalweapons'!
Exit Code: -1

I already tried downloading the latest version of fabric api

**Comment by Globox1997** [comment]
did you install cloth config api?

**Comment by Skeithh** [comment]
Also suffering the same error, using the "Survival of Origins" modpack on Curseforge.
Tried the following:
- Updated fabric API
- Updated Medieval origins to 1.1.7 since the one in the modpack was outdated
- Checked if Pehkui in the modpack was up to date
- Tried updating clothconfig API

None of the attempts worked so for now we temporarily removed the mod from the pack. Crashlog attached
[crash-2021-10-05_16.56.59-client.txt](https://github.com/Globox1997/MedievalWeapons/files/7286982/crash-2021-10-05_16.56.59-client.txt)

**Comment by Globox1997** [comment]
@Skeithh in the crash log you are using not the latest fabric api, it has to be 0.40.1+

**Comment by Skeithh** [comment]
@Globox1997 
Oh woops- that was a crashlog from when we were trying older versions of the API to see if the game would launch. Just eyed around and it seems that the newer crashes are unrelated to the mod so apologies for that-
Will drop what the output log gave me here just in case it IS related though
[output log crash 2021-10-06.txt](https://github.com/Globox1997/MedievalWeapons/files/7293515/output.log.crash.2021-10-06.txt)
.

**Comment by Globox1997** [comment]
This is not a full crash log and doesn't say anything
